name: 'Create Informational Syschange'
description: 'Create an Informational Syschange'
inputs:
  summary:
    description: 'Summary of change'
    required: true
  author:
    description: 'GitHub username of triggering user'
    required: true
  group:
    description: 'Syschange responsible group name'
    required: true
  affectedServices:
    description: 'Comma-separated list of Atlassian IDs for the affected services'
    required: true
  apiKey:
    description: 'Atlassian API Key'
    required: true
  description:
    description: 'Description of change'
    required: false
    default: ''
  installer:
    description: "Syschange installer Atlassian ID"
    required: false
    default: '712020:db823f4a-761e-42b7-aff2-bcd0a391c480'
  affectedIntegrations:
    description: 'Comma-separated list of Atlassian IDs for the affected integrations'
    required: false
outputs:
  ticket-link:
    description: 'URL of created Informational Syschange'
    value: ${{ steps.syschange.outputs.ticket-url }}

runs:
  using: "node20"
  main: "dist/index.js"
