name: 'Create Informational Syschange'
description: 'Create an Informational Syschange'
inputs:
  summary:
    description: 'Summary of change'
    required: true
  apiKey:
    description: 'Atlassian basic auth'
    required: true
  description:
    description: 'Description of change'
    required: false
    default: ''
  installer:
    description: "Syschange installer Atlassian ID"
    required: false
    default: '5a1c643d2939341a89906a9b'
  group:
    description: 'Syschange responsible group name'
    required: false
    default: 'OIT-JSM-Web Services'
outputs:
  ticket-link:
    description: 'URL of created Informational Syschange'
    value: ${{ steps.syschange.outputs.ticket-url }}

runs:
  using: "composite"
  steps:
    - name: Get current time
      run: echo "NOW=$(date -u +%FT%TZ)" >> $GITHUB_ENV
      shell: bash

    - name: Create Informational Syschange
      id: syschange
      env:
        ISSUE_TYPE_ID: '10014' # [System] Informational Change 
        RESPONSIBLE_GROUP: 'customfield_10058'
        PLANNED_START: 'customfield_10107'
        PLANNED_END: 'customfield_10049'
        REQUEST_TYPE: 'customfield_10010'
        INFORMATIONAL_SYSTEM_CHANGE: '74'
        CHANGE_TYPE: 'customfield_10106'
        INFORMATIONAL_CHANGE_ID: '10192'
      shell: bash
      run: |
        RESPONSE=$(curl --header 'Content-Type: application/json' \
          --request POST \
          --user ${{ inputs.apiKey }} \
          --data '{"fields": {
            "summary": "${{ inputs.summary }}",
            "description": "${{ inputs.description }}",
            "reporter": {
              "id": "${{ inputs.installer }}"
            },
            "${{ env.RESPONSIBLE_GROUP }}": {
              "name": "${{ inputs.group }}"
            },
            "${{ env.PLANNED_START }}": "${{ env.NOW }}",
            "${{ env.PLANNED_END }}": "${{ env.NOW }}",
            "project": {
              "key": "SYS"
            },
            "issuetype": {
              "id": "${{ env.ISSUE_TYPE_ID }}"
            },
            "${{ env.REQUEST_TYPE }}": "${{ env.INFORMATIONAL_SYSTEM_CHANGE }}",
            "${{ env.CHANGE_TYPE }}": {
              "id": "10192"
            }
          }}' \
          https://brown.atlassian.net/rest/api/2/issue)
        TICKET_KEY=$(echo "$RESPONSE" | grep -o 'SYS-[0-9]*')
        echo "::set-output name=ticket-url::https://brown.atlassian.net/browse/$TICKET_KEY"
