name: 'Create Informational Syschange'
description: 'Create an Informational Syschange'
inputs:
  summary:
    description: 'Summary of change'
    required: true
  author:
    description: 'GitHub username of triggering user'
    required: true
  group:
    description: 'Syschange responsible group name'
    required: true
  affectedService:
    description: 'Atlassian ID for the affected service'
    required: true
  apiKey:
    description: 'Atlassian API Key'
    required: true
  description:
    description: 'Description of change'
    required: false
    default: ''
  installer:
    description: "Syschange installer Atlassian ID"
    required: false
    default: '5a1c643d2939341a89906a9b'
outputs:
  ticket-link:
    description: 'URL of created Informational Syschange'
    value: ${{ steps.syschange.outputs.ticket-url }}

runs:
  using: "composite"
  steps:
    - name: Get current time
      run: echo "NOW=$(date -u +%FT%TZ)" >> $GITHUB_ENV
      shell: bash

    - name: Create Informational Syschange
      id: syschange
      env:
        ISSUE_TYPE_ID: '10014' # [System] Informational Change 
        RESPONSIBLE_GROUP: 'customfield_10058'
        GITHUB_ID: 'customfield_10392'
        PLANNED_START: 'customfield_10107'
        PLANNED_END: 'customfield_10049'
        REQUEST_TYPE: 'customfield_10010'
        AFFECTED_SERVICE: 'customfield_10171'
        INFORMATIONAL_SYSTEM_CHANGE: '74'
        WORKSPACE_ID: '3015eb17-fcd8-4eb8-b534-dfbce48cd828'
      shell: bash
      run: |
        RESPONSE=$(curl --header 'Content-Type: application/json' \
          --silent
          --request POST \
          --user ${{ inputs.apiKey }} \
          --data '{"fields": {
            "summary": "${{ inputs.summary }}",
            "description": "${{ inputs.description }}",
            "reporter": {
              "id": "${{ inputs.installer }}"
            },
            "${{ env.RESPONSIBLE_GROUP }}": {
              "name": "${{ inputs.group }}"
            },
            "${{ env.AFFECTED_SERVICE }}": [{
              "id": "${{ env.WORKSPACE_ID }}:${{ inputs.affectedService }}"
            }],
            "${{ env.GITHUB_ID }}": "${{ inputs.author }}",
            "${{ env.PLANNED_START }}": "${{ env.NOW }}",
            "${{ env.PLANNED_END }}": "${{ env.NOW }}",
            "project": {
              "key": "SYS"
            },
            "issuetype": {
              "id": "${{ env.ISSUE_TYPE_ID }}"
            },
            "${{ env.REQUEST_TYPE }}": "${{ env.INFORMATIONAL_SYSTEM_CHANGE }}"
          }}' \
          https://brown.atlassian.net/rest/api/2/issue)
        TICKET_KEY=$(echo "$RESPONSE" | grep -o 'SYS-[0-9]*')
        echo "ticket-url=https://brown.atlassian.net/browse/$TICKET_KEY" >> $GITHUB_OUTPUT
